name: Print Hello World
on:
  push:
jobs:
  print:
    runs-on: macOS-latest
    steps:
      - name: Print Hello
        run: echo "Hello World"

  second-job:
    print:
      runs-on: macOS-latest
      steps:
        - name: Say HI
          run: echo "HI"

on:
  push:
    jobs:
      print:
        runs-on: macOS-latest
        steps:
          - name: list files
            run: ls -a